# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "11:00"
      timezone: "Asia/Tokyo"
    labels:
      - "build"
      - "dependencies"
      - "github_actions"
    assignees:
      - "dependabot"
    reviewers:
      - "ginokent"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:00"
      timezone: "Asia/Tokyo"
    labels:
      - "build"
      - "dependencies"
      - "go"
    assignees:
      - "dependabot"
    reviewers:
      - "ginokent"

  - package-ecosystem: "gomod"
    directory: "/grpc"
    schedule:
      interval: "daily"
      time: "11:00"
      timezone: "Asia/Tokyo"
    labels:
      - "build"
      - "dependencies"
      - "go"
    assignees:
      - "dependabot"
    reviewers:
      - "ginokent"

  - package-ecosystem: "gomod"
    directory: "/integrationtest"
    schedule:
      interval: "daily"
      time: "11:00"
      timezone: "Asia/Tokyo"
    labels:
      - "build"
      - "dependencies"
      - "go"
    assignees:
      - "dependabot"
    reviewers:
      - "ginokent"
