# https://docs.github.com/ja/repositories/releasing-projects-on-github/automatically-generated-release-notes
changelog:
  categories:
    - title: "BREAKING CHANGES"
      labels:
        - BREAKING CHANGE
    - title: "Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)"
      labels:
        - build
        - dependencies
    - title: "Changes to our CI configuration files and scripts (examples: CircleCi, SauceLabs)"
      labels:
        - ci
    - title: "Documentation only changes"
      labels:
        - docs
    - title: "A new feature"
      labels:
        - feat
    - title: "A bug fix"
      labels:
        - fix
    - title: "A code change that improves performance"
      labels:
        - perf
    - title: "A code change that neither fixes a bug nor adds a feature"
      labels:
        - refactor
    - title: "Adding missing tests or correcting existing tests"
      labels:
        - test
    - title: "Changes to the build process or auxiliary tools and libraries such as documentation generation"
      labels:
        - chore
    - title: "Other Changes"
      labels:
        - "*"
