// Code generated by "stringer -linecomment -type Algorithm"; DO NOT EDIT.

package jwa

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HS256-0]
	_ = x[HS384-1]
	_ = x[HS512-2]
	_ = x[RS256-3]
	_ = x[RS384-4]
	_ = x[RS512-5]
	_ = x[ES256-6]
	_ = x[ES384-7]
	_ = x[ES512-8]
	_ = x[PS256-9]
	_ = x[PS384-10]
	_ = x[PS512-11]
	_ = x[None-12]
}

const _Algorithm_name = "HS256HS384HS512RS256RS384RS512ES256ES384ES512PS256PS384PS512none"

var _Algorithm_index = [...]uint8{0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 64}

func (i Algorithm) String() string {
	if i < 0 || i >= Algorithm(len(_Algorithm_index)-1) {
		return "Algorithm(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Algorithm_name[_Algorithm_index[i]:_Algorithm_index[i+1]]
}
