name: label-checker

on:
  pull_request:
    types:
      - opened
      - edited
      - labeled
      - ready_for_review
      - reopened
      - synchronize

env:
  LABELS: "BREAKING CHANGE,build,ci,docs,feat,fix,perf,refactor,test,chore"

jobs:
  check:
    name: Check labels
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      statuses: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }} # needed for gh pr view
      - name: Check labels
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          # Check labels
          set -Eeuo pipefail -x

          # If any of the labels are present, exit with success
          if [[ -n "$(gh pr view --json labels --jq ".labels[].name")" ]]; then
            exit 0
          fi

          # Add labels based on PR title
          GH_PR_TITLE=$(gh pr view --json title --jq .title)
          gh label list --json name --jq ".[].name" | while read -r LINE; do echo "${GH_PR_TITLE:?}" | awk -F: "/^${LINE-}:/ {print \$1}" ; done | xargs -t -I{} gh pr edit --add-label {}

          # If any of the labels are present, exit with success
          while read -r LINE; do
            if grep -E "$(tr , "|" <<<"${LABELS:?}")" <<<"${LINE-}"; then
              exit 0
            fi
          done <<<"$(gh pr view --json labels --jq ".labels[].name")"

          # If none of the labels are present, exit with error
          exit 1
